//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace Domain
{
    public class Course
    {
        public virtual int Id
        {
            get;
            set;
        }

        public virtual List<Resultat> ListeResultat
        {
            get;
            set;
        }

        public virtual IList<Participant> ListeParticipants
        {
            get;
            set;
        }
        public virtual List<Resultat> Classement
        {
            get;
            set;
        }
        public virtual double Distance
            //En km
        {
            get;
            set;
        }
        public Course()
        {

        }
        public Course(double distance)
        {
            Distance = distance;
            ListeResultat = new List<Resultat>();
            ListeParticipants = new List<Participant>();
        }
        public virtual void ClasserResultats()
        {
            // Tri les résultats du plus petit au plus grand et modifie le classement du resultat
            ListeResultat = ListeResultat.OrderByDescending(r => r.Temps).ToList();
            foreach(Resultat r in ListeResultat)
            {
                r.Classement = ListeResultat.IndexOf(r);
            }
        }

        public override string ToString()
        {
            return "Course - Distance : " + Distance+ " m";
        }

    }
}


