//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Course
{
	public virtual string Id
	{
		get;
		set;
	}

	public virtual List<Resultat> ListeResultat
	{
		get;
		set;
	}

	public virtual Resultat Resultat
	{
		get;
		set;
	}

	public virtual void ClasserResultats()
	{
		throw new System.NotImplementedException();
	}

}

