//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Resultat
{
	public virtual int Id_participant
	{
		get;
		set;
	}

	public virtual int Id
	{
		get;
		set;
	}

	public virtual int Classement
	{
		get;
		set;
	}

	public virtual double VitMoy
	{
		get;
		set;
	}

	public virtual double AllureMoy
	{
		get;
		set;
	}

	public virtual Course Course
	{
		get;
		set;
	}

	public virtual Participant Participant
	{
		get;
		set;
	}

	public Resultat()
	{
	}

}

