//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Utilisateur
{
	public virtual string Pseudo
	{
		get;
		set;
	}

	public virtual string Mdp
	{
		get;
		set;
	}

	public virtual int Id
	{
		get;
		set;
	}

	public Utilisateur()
	{
	}

	public Utilisateur(string pseudo, string mdp)
	{
	}
    

}

